### PR TITLE
Cleanup and minor improvements

### PR DESCRIPTION
**Pull request by dodexahedron**
This is primarily code cleanup and organization, as I did in the SEModAPI project.
I've also merged in the contribution made by valadian a couple weeks ago.

There's also a commit in here that fixes an incompatibility with one of my commits to SEModAPI, which changed a property name.

### CODE REVIEW

**Comment by dodexahedron** [comment]
This version, along with my latest pushed version of SEServerExtender, are currently running on our server with no issues.

**Comment by joshuataylor** [comment]
Wow, lots of commits, can you rebase to make it easier to review?

**Comment by joshuataylor** [comment]
I believe Core.cs needs to be changed:
`		public void OnChatReceived(ChatManager.ChatEvent obj)
		{
			if (obj.message[0] != '/')
				return;
			HandleChatMessage(obj.sourceUserId, obj.message);
		}
`

**Comment by dodexahedron** [comment]
That was the update I referred to in 0336b83.  You need my latest copy of the mod API as well, for that to compile (hence the version dependency note update).

As for the number of commits, don't let it scare you.  They're all small, so the changes are isolated.  Should be pretty easy to follow.

**Comment by dodexahedron** [comment]
I guess I should say they're all small except for the ones where I did the same cleanup on all files, such as removing all redundant using statements.  Those are kind of huge, but they're isolated so that's all that happened in those commits.  I don't believe in single large commits that have 50 different changes in them.

**Comment by joshuataylor** [comment]
Ah perfect, thanks @dodexahedron - I didn't see your other PR, so going to compile that locally.

Awesome changes so far btw +1

**Comment by dodexahedron** [comment]
Just a warning that there are likely to be a few more breaking changes coming up, soon, so it'll be important to keep both repositories synced to ensure both SESE and Essentials compile and work together until it can get to a more stable place.  Yay for alpha!

**Comment by Tyrsis** [comment]
I will review the merges today and roll them into master.  Thanks for the cleanup, something I just haven't had time to do! ;)

**Comment by dodexahedron** [comment]
I've got a lot more coming.  I'm trying to keep the breaking changes to a minimum, just to be a good citizen, but this IS an alpha, after all. :grinning:

**Comment by dodexahedron** [comment]
So that I don't make life too difficult for you, if you're working on something specific... Are you working on anything specific at the moment?  I'll try to stay away from heavy modifications to specific files you're using, if so, since some merges might be a little difficult with all the naming changes and such.

**Comment by Tyrsis** [comment]
Yes I work on this constantly, and major modification should be avoided.

**Comment by dodexahedron** [comment]
No problem. Will merge whenever you push.

**Comment by dodexahedron** [comment]
I'll go ahead and do the pull/merge/push dance, now.

**Comment by dodexahedron** [comment]
Version 1.1.0.2181 will be released in binary form on my fork shortly.

**Comment by dodexahedron** [comment]
Get it here:
https://github.com/dodexahedron/EssentialsPlugin/releases/tag/v1.1.0.2181-alpha

**Pull request closed without merging**
